'use client';
import Link from 'next/link'; import {useCallback,useEffect,useMemo,useState} from 'react'; import MarketChart from '@/components/MarketChart';

type M={slug:string;name:string;price:number|null;change:number|null;changePct:number|null;time:string|null;unit:string;category:string}; type Bubble={slug:string;name:string;value:number|null;changePct:number|null};
const f=(n:number|null)=>n==null?'—':new Intl.NumberFormat('fa-IR').format(n); const pc=(n:number|null)=>n==null?'—':`${n>0?'+':''}${n.toLocaleString('fa-IR',{maximumFractionDigits:2})}%`;
export default function Home(){const [markets,setMarkets]=useState<M[]>([]),[bubbles,setBubbles]=useState<Bubble[]>([]),[q,setQ]=useState(''),[history,setHistory]=useState<any[]>([]),[selected,setSelected]=useState('geram18'),[ai,setAi]=useState(''),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{try{const [a,b,h]=await Promise.all([fetch('/api/markets',{cache:'no-store'}),fetch('/api/bubbles',{cache:'no-store'}),fetch(`/api/history/${selected}`,{cache:'no-store'})]);const aj=await a.json(),bj=await b.json(),hj=await h.json();setMarkets(aj.markets||[]);setBubbles(bj.bubbles||[]);setHistory(hj.history||[]);}finally{setLoading(false)}},[selected]); useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[load]);
 const filtered=useMemo(()=>markets.filter(x=>`${x.name} ${x.category}`.includes(q)),[markets,q]); const current=markets.find(x=>x.slug===selected); async function analyze(){setAi('در حال تحلیل...');const r=await fetch('/api/ai/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({selected,current,markets,bubbles,history})});const j=await r.json();setAi(j.analysis||j.message||j.error||'پاسخی دریافت نشد.');}
 return <main className="shell"><header className="topbar"><div className="brand">بازار <span>طلا</span></div><div className="live"><i className="dot"/> دریافت لحظه‌ای از TGJU</div></header>
 <section className="hero"><div><div className="muted">داشبورد هوشمند بازار</div><h1>قیمت طلا، سکه، دلار و اونس</h1><p className="muted">داده‌ها هر ۱۵ ثانیه تازه می‌شوند؛ برای تاریخچه از آرشیو TGJU استفاده می‌شود.</p></div><div className="hero-actions"><button className="btn" onClick={load}>بروزرسانی</button><button className="btn primary" onClick={analyze}>تحلیل هوشمند</button></div></section>
 <input className="search" placeholder="جستجوی طلا، سکه، دلار..." value={q} onChange={e=>setQ(e.target.value)}/>
 <section className="cards">{filtered.map(m=><Link key={m.slug} href={`/market/${m.slug}`} className="card"><div className="card-title">{m.name}</div><div className="price">{loading?'...':f(m.price)}</div><div className={`change ${(m.changePct??0)>0?'up':(m.changePct??0)<0?'down':'neutral'}`}>{pc(m.changePct)} <span className="muted">{m.unit}</span></div></Link>)}</section>
 <section className="section"><div className="section-head"><h2>روند {current?.name||'بازار'}</h2><span className="muted">۶۰ رکورد اخیر</span></div><div className="panel"><MarketChart data={history}/><div className="axis"><span>{history[0]?.date||'—'}</span><span>{history.at(-1)?.date||'—'}</span></div></div></section>
 <section className="section detail-grid"><div className="panel"><div className="section-head"><h2>حباب سکه</h2><span className="muted">داده TGJU</span></div>{bubbles.map(b=><div className="bubble" key={b.slug}><span>{b.name}</span><strong>{f(b.value)} <small className={(b.changePct??0)>=0?'up':'down'}>{pc(b.changePct)}</small></strong></div>)}</div><div className="panel ai"><div className="section-head"><h2>🤖 تحلیل هوشمند</h2><button className="btn" onClick={analyze}>تحلیل</button></div><div className="ai-result">{ai||'با دکمه «تحلیل هوشمند»، داده لحظه‌ای، روند، تغییرات و حباب برای Agent Manager ارسال می‌شود.'}</div></div></section>
 <footer className="footer"><span>منبع داده: TGJU</span><span>آخرین دریافت: {new Date().toLocaleTimeString('fa-IR')}</span></footer></main>}
